### ISSUE TITLE
Documentation Wrong

### ISSUE THREAD

**Issue by jwkellyiii** [elliotttf/express-request-version#65]
The documentation for setByPath is wrong. It states you use `setVersion('/base')` but the RegExp used will not match it. The RegExp that is generated is `^\/base\/(v?\d+(\.\d+){0,2}[^\/]*)` which will only match `setVersion('/base/')`. The end `/` is extremely important.

**Comment by elliotttf** [comment]
Whoops! Thank you, fix incoming 🍻
